<a href="https://colab.research.google.com/github/starsyntaxx/tracy_hackathon/blob/main/01_EDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
import zipfile
import os

# Upload file from your laptop
uploaded = files.upload()

# Get uploaded filename
zip_file = list(uploaded.keys())[0]

# Create extraction folder
extract_folder = "dataset"

# Unzip the file
with zipfile.ZipFile(zip_file, 'r') as zip_ref:
    zip_ref.extractall(extract_folder)

print(f"Dataset extracted to: {os.path.abspath(extract_folder)}")

# View extracted files
for root, dirs, files in os.walk(extract_folder):
    for file in files[:5]:  # show first few files
        print(os.path.join(root, file))

Saving data-20260615T111051Z-3-001.zip to data-20260615T111051Z-3-001.zip
Dataset extracted to: /content/dataset
dataset/data/mobility.csv
dataset/data/vitals.csv
dataset/data/contact_tracing.csv

In [2]:
import pandas as pd

In [3]:
# Read the CSV file
df_mobility = pd.read_csv("dataset/data/mobility.csv")
df_vitals = pd.read_csv("dataset/data/vitals.csv")
df_data = pd.read_csv("dataset/data/contact_tracing.csv")

In [10]:
df_data.head()

,user_id,date,time,latitude,longitude,geohash,mac,rssi,proximity
0,U002,2023-10-19,18:06:01,7.680377,6.418345,s1kedn1tq,D13941,-1,unscored
1,U002,2023-10-19,18:06:01,7.680377,6.418345,s1kedn1tq,D13227,8,close
2,U002,2023-10-19,18:06:01,7.680377,6.418345,s1kedn1tq,D21917,-1,unscored
3,U002,2023-10-19,18:06:01,7.680377,6.418345,s1kedn1tq,D19180,-1,unscored
4,U003,2023-10-20,06:12:13,5.374891,6.998611,s0uyx62pp,D05480,7,close

In [23]:
df_data['rssi'].unique()

array([ -1,   8,   7,  12,   6,   9,  -5, -21,   4,  11,  24, -11,   2,
       -10,   1,   0,   5, -15, -20,   3,  26])

In [26]:
df_data['geohash'].nunique()

6721

In [27]:
df_data['latitude'].nunique()

12227

In [24]:
df_data['rssi'].value_counts()

rssi
-1     72858
 12    29717
 8      5931
 7      3940
 11     2746
 6      2071
-5       718
 4       352
-11      324
 9       270
 5       171
 24       81
 2        50
 1        36
-10       32
-21       22
 0         8
 26        5
-15        4
-20        1
 3         1
Name: count, dtype: int64

In [11]:
df_data['user_id'].nunique()

88

In [19]:
df_data['date'].nunique()

51

In [15]:
user_date = df_data['date'].value_counts()
print(user_date)

date
2023-10-23    22720
2023-11-05    13438
2023-11-06     9599
2023-10-20     6830
2023-11-04     6793
2023-10-21     5615
2023-10-25     5446
2023-11-03     5059
2023-10-31     4038
2023-11-17     3763
2023-11-07     3637
2023-10-24     3558
2023-10-22     3452
2023-10-27     2932
2023-11-01     2700
2023-11-16     2090
2023-11-09     2031
2023-10-26     1748
2023-11-15     1592
2023-10-30     1570
2023-11-11     1458
2023-10-28     1114
2023-11-20      965
2023-12-18      839
2023-11-02      832
2023-11-26      809
2023-11-14      755
2023-12-11      626
2023-12-06      567
2023-11-08      471
2023-11-19      421
2023-11-10      399
2023-11-28      220
2023-11-13      202
2023-11-23      152
2023-12-09      146
2023-11-27      131
2023-11-29      122
2023-11-18      111
2023-11-22      103
2023-10-29       60
2023-11-12       58
2023-11-21       43
2023-12-10       37
2023-12-08       33
2023-12-15       25
2023-12-13       21
2023-10-19        4
2023-12-03        1
2023-11-24        1
2023-12-02        1
Name: count, dtype: int64

In [36]:
df_filtered = df_data[df_data['rssi'] >= 5]

df_filtered.head()

,user_id,date,time,latitude,longitude,geohash,mac,rssi,proximity,timestamp
1,U002,2023-10-19,18:06:01,7.680377,6.418345,s1kedn1tq,D13227,8,close,2023-10-19 18:06:01
4,U003,2023-10-20,06:12:13,5.374891,6.998611,s0uyx62pp,D05480,7,close,2023-10-20 06:12:13
5,U003,2023-10-20,06:12:13,5.374891,6.998611,s0uyx62pp,D13423,7,close,2023-10-20 06:12:13
6,U003,2023-10-20,06:12:13,5.374891,6.998611,s0uyx62pp,D07028,12,close,2023-10-20 06:12:13
10,U003,2023-10-20,06:12:43,5.375526,6.998862,s0uyx686t,D05480,7,close,2023-10-20 06:12:43

In [34]:

df_filtered['mac'].nunique()

8109

In [30]:
print("Original shape:", df_mobility.shape)
print("Filtered shape:", df_filtered.shape)

Original shape: (50737, 11)
Filtered shape: (44932, 9)

stimullaate network graph

In [31]:
# combine date + time into timestamp
df_data['timestamp'] = pd.to_datetime(df_data['date'] + ' ' + df_data['time'])

df_data.head()

,user_id,date,time,latitude,longitude,geohash,mac,rssi,proximity,timestamp
0,U002,2023-10-19,18:06:01,7.680377,6.418345,s1kedn1tq,D13941,-1,unscored,2023-10-19 18:06:01
1,U002,2023-10-19,18:06:01,7.680377,6.418345,s1kedn1tq,D13227,8,close,2023-10-19 18:06:01
2,U002,2023-10-19,18:06:01,7.680377,6.418345,s1kedn1tq,D21917,-1,unscored,2023-10-19 18:06:01
3,U002,2023-10-19,18:06:01,7.680377,6.418345,s1kedn1tq,D19180,-1,unscored,2023-10-19 18:06:01
4,U003,2023-10-20,06:12:13,5.374891,6.998611,s0uyx62pp,D05480,7,close,2023-10-20 06:12:13

In [ ]:
import matplotlib.pyplot as plt
import numpy as np